version: '3'
services:
  master:
    image: my-locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_MODE=master
      - MIN_USERS=10
      - MAX_USERS=300
      - CYCLE_TIME=30
      - SPAWN_RATE=10
    command: >
      -f /mnt/locust/test/locustfile.py --host http://host.docker.internal:3001 --master

  worker:
    image: my-locust
    environment:
      - LOCUST_MODE=worker
      - MIN_USERS=10
      - MAX_USERS=300
      - CYCLE_TIME=30
      - SPAWN_RATE=10
    command: >
      -f /mnt/locust/test/locustfile.py --host http://host.docker.internal:3001 --worker --master-host master
    depends_on:
      - master
    scale: 4